### ISSUE TITLE
[11월 셋째주] Feature/login 

### ISSUE THREAD

**Issue by live-small** [Instagram-Clone-Coding/React_instagram_clone#15]
## 목표 
로그인 화면 퍼블리싱  완료 
`작업 브랜치 : feature/login`

## Todo
- [x] 코드리뷰 코멘트 달기 
- 코드리뷰 내용 반영 
     - [x] 라우터 수정 
     - [x] 페이스북 로그인버튼 패딩 없애기 
     - [x] 파일 구조, 파일명 통일 
     - [ ]  input focus 
- [x] footer 퍼블리싱
- [x]  로그인 버튼 활성화
- [x]  입력한 비밀번호 보이기 버튼 추가
