### ISSUE TITLE
DM 페이지 기능 추가 요청

### ISSUE THREAD

**Issue by seonpilKim** [Instagram-Clone-Coding/React_instagram_clone#52]
### DM 받는사람 검색 기능 추가
![image](https://user-images.githubusercontent.com/68049320/164804242-e915a2f3-c4a0-4422-8de7-c50f7658f11d.png)
- 유저를 검색해서 DM을 보낼 수 있는 기능을 추가해 주세요. (단톡 가능)
- [API](http://ec2-3-36-185-121.ap-northeast-2.compute.amazonaws.com:8080/swagger-ui.html#/%EC%B1%84%ED%8C%85_API)
    - 검색 API: `검색(/topsearch)` 
    - 채팅 API: `채팅방 생성(/chat/rooms)`
### DM 메시지 박스 사라지는 기능 추가
![image](https://user-images.githubusercontent.com/68049320/164807034-61671c97-4da9-4d49-9a0d-b73582688563.png)
- 포커싱이 풀리면 해당 박스가 사라지는 기능을 추가해 주세요.
### DM에서 상대방 클릭 시, 프로필 페이지로 이동하는 기능 추가
![image](https://user-images.githubusercontent.com/68049320/164808936-6ae0d3a2-445d-4977-9c9c-af9a374500e8.png)
- 표시한 부분을 클릭하면, 대상 프로필 페이지로 이동하는 기능을 추가해 주세요.
![image](https://user-images.githubusercontent.com/68049320/164811210-5a08c6b2-063e-4a81-853a-2e3a91ad4aa8.png)
- 단체 채팅방의 상세 정보 창도 추가해 주세요.
- 채팅방 이름(그룹 이름) 변경 API, 채팅 나가기 API는 다음 주 중으로 구현 후 전달 드리겠습니다.

## Todo
- [x] DM 받는사람 검색 기능 추가
- [x] DM 메시지 박스 사라지는 기능 추가
- [x] DM에서 상대방 클릭 시, 프로필 페이지로 이동하는 기능 추가

**Comment by okinawaa** [comment]
DM 받는사람 검색 기능 추가

선필님 안녕하세요 dl 라는 키워드로 검색했을때 빈배열이 돌아오는게 맞나요!? 
dlwlrma1 이나 dlwlrma2 가 나와야하지 않나요!?

**Comment by okinawaa** [comment]
DM 메시지 박스 사라지는 기능 추가

선필님 채팅시에 상대방의 상단의 프로필이 아닌 상대방이 보낸 채팅메세지 왼쪽에 작게 상대방의 프로필사진이 있고 그것을 클릭했을때 그 사람의 프로필페이지로 이동하기 위해서는 그사람의 username 도 MessageDTO 에 포함되어야할것 같습니다! username 도 추가해주셔서 메세지 조화할때 주시면 감사하겠습니다~!

**Comment by okinawaa** [comment]
단체채팅 구현은 개인채팅을 좀더 견고하게 진행한 후 진행하도록 하겠습니다!

**Comment by okinawaa** [comment]
세가지 기능 모두 구현완료하였습니다.
https://github.com/Instagram-Clone-Coding/React_instagram_clone/pull/53
